### PR TITLE
Allow the user handling portion of JsonProvider to be overridden in a subclass

### PR DESCRIPTION
**Pull request by dantman**
This should permit roles to be defined in JSON config but user roles to come from a database.

### CODE REVIEW

**Comment by yanickrochon** [comment]
Thank you for contributing! However this seems like a redundant method since `getRoles(user)` is already meant to be overridden. I don't yet have the need to implement a `Provider` for a database, but the idea behind the `JsonProvider` is that it is a synchronous implementation. What you are suggesting, or rather what you'd really need is a compound `Provider`. Something in the line of :

```js
class CompoundProvider extends Provider {
  constructor(dbAdapter, jsonRules, cache) {
    this._dbAdapter = dbAdapter;
    this._jsonProvider = new JsonProvider(jsonRules);
    this._cache = cache;
  }

  getRoles(user) {
    return Promise.resolve(this._cache.get(user)).then(userRoles => {
      return userRoles || this._dbAdapter.getUserRoles(user).then(userRoles => {
        this._cache.set(user, userRoles);
        return userRoles;
      });
    }).then(userRoles => {
      return this._jsonProvider.getRoles(user);
    });
  }

  getPermissions(role) {
    return this._jsonProvider.getPermissions(role);
  }

  getAttributes(role) {
    return this._jsonProvider.getAttributes(role);
  }
}
```

This is, in fact, pretty much the implementation that I use for the project that this module was originally written for.

**Comment by dantman** [comment]
A compound provider that uses another provider is an interesting idea I hadn't thought of.

However all I'm trying to do is decouple the part of JsonProvider#getRoles that reads a user's roles from a hardcoded object from the part that recursively resolves roles.

My goal of using rbac with a database is not to fetch the user from within the provider, it's for use within a `koa-rbac` middleware flow where the user for the session has already been fetched from the database and the `user` that the provider is passed is a user object that already knows what its roles are (or other synchronous cases like a signed JWT that includes the roles array as part of the signed payload).

ie: Where the `getUserRoles` implementation someone may use in a subclass is actually a synchronus task as simple as something like:
```js
  getUserRoles(user) {
    return user.roles;
  }
```
*(Where `user.roles` may vary depending on what your User class looks like: `user.groups`, `user.getRoles()`, `[user.role]`, `[user.admin ? 'admin' : 'guest']`)*

I really do not like the need to modify `_rules.users` from the custom provider, it is a bad idea in a number of ways:
* Custom providers are messing with private `_` variables instead of a proper interface.
* The code becomes much more complex than it needs to be (assign values to private object, pass key to JsonProvider, JsonProvider reads from private object using that key; vs. "return values")
* If you don't take care to clean up `_rules.users` later and you have a pile of users, then the object will grow and grow, worthlessly duplicating a portion of the database (since it's always overwritten and never reused) and leaking memory.
* While technically there is no race condition since `_rules.users` is written before synchronously calling `getRoles`, the fact that _rules is a shared object being given per-request state that another function is supposed to operate on really rubs me the wrong way.

**Comment by dantman** [comment]
The alternate idea I had to `getUserRoles` was to instead move the `collect` portion into another method. Not sure what it'd be named (`collectRoles`, `expandRoles`, ...), but then `getRoles` would be something simple like:
```js
getRoles(user) {
  const rules = this._rules || {};
  return this.collectRoles(rules['users'] && rules['users'][user] || []);
}
```

Overriding that would require always calling the `collectRoles` method yourself, but otherwise would be just as easy to override as `getUserRoles`:
```js
getRoles(user) {
  return this.collectRoles(user.roles);
}
```

**Comment by yanickrochon** [comment]
Right, then moving the `collect` inner function to a "private" class method of the `Provider` "interface" would be preferable to me, then, and I'd agree with this PR on your described basis.

**Comment by dantman** [comment]
Do you mean classes overriding `getRoles` would have to call `this._collectRoles()` or the interface for `getRoles()` would be changed so it returns a simple array and Provider is responsible for implicitly doing recursive collection of roles on the array?

**Comment by yanickrochon** [comment]
Yes. using the suggested method signature in my last comment, so it would be available to any implementing `Provider`. Once the `userRoles` array is known, and all `roles` are defined, it really doesn't require anything but a simple synchronous function call, and `collect` is the implementation that would be "exposed" from the abstract class, so all `Provider` return a uniform result without requiring re-implementing the algorithm.

**Comment by dantman** [comment]
You're already using node 4+ only class syntax, would you mind if I refactored the code to use arrow functions and for..of over arrays? The `for(;;)` array iteration especially makes the algorithms used more opaque.

Alternatively, if you don't mind pre-compiling the library with babel, async/await would make the promise logic much cleaner.

**Comment by yanickrochon** [comment]
Thanks, but until arrow functions are as fast as legacy function calls, I am not interested to use them in this module yet, so the code runs as fast as possible. Some may say that micro-optimizations are not that important, but I'm not convinced about the benefit of using this feature at the moment, and save a merely one or two lines of code for the sake of "code readability" or something :smile: .

**Comment by dantman** [comment]
micro-optimization on arrow funcs is pretty pointless when using native Promises and when using babel where arrow functions get transpiled so they work exactly like non-arrow functions, but w/e.

I'm finishing up an alternative proposal that should also make other custom provider implementations cleaner and more abstract.

**Comment by dantman** [comment]
How is this so far?

I changed the provider interface to:
- getRoleHierarchy(user)
- getRoles(user):Array<string>
- getInheritedRoles(role):Array<string>
- getPermissions(role):Array<string>
- getAttributes(role):Array<string>

`getPermissions` and `getAttributes` are the same as before.

A provider can now be low or high level:
- A low level provider overrides `getRoleHierarchy` and directly outputs the nested object of roles
- A high level provider implements `getRoles(user)` returning an array of roles for a user and `getInheritedRoles(role)` returning an array of roles inherited by another (the default `getRoleHierarchy` implementation takes care of collecting those into the role hierarchy)

I can still make a few modifications to this:
- Right now it's a breaking change since `getRoles` was renamed to `getRoleHierarchy`; It should be possible to retain compatibility for old providers by making `getRoleHierarchy` check the return value of getRoles and emit a deprecation notice. (if so, what would you like to emit the deprecation notice using, console.warn/another npm module?)
- Right now `getInheritedRoles` only works synchronously while the rest of provider methods are allowed to return promises; I could change the collect algorithm so it works when `getInheritedRoles` returns a promise.

**Comment by yanickrochon** [comment]
I am not 100% convinced about `getRoles(user)` and `getInheritedRoles(role)` and, consequently, `getRoleHierarchy(user)`. The reason why I initially wrote 3 abstract methods was to provide the 3 fundamental operations that rbac-a requires to function; role attributes, role permissions, and user roles. That in mind, some structures (i.e. a roles tree) may already be returned by some RDBMS, or even NoSQL databases, in a single query. So there is really no need to have a method to return inherited roles.... If we can get all pertinent roles and information from a single call, all the better! This is why all three methods support returning of a `Promise` instance or a direct value, because some providers may execute SQL queries, etc. or return data directly, depending on it's implementation and requirements. So methods are defined to be as concise as possible. If the rbac-a module doesn't require any extra methods (it really does not), such methods should not be defined in the abstract class. It doesn't mean that providers cannot define any extra methods, and I can very well see the proposed methods for systems that may use the same provider to fulfill more responsibilities in the application.

I understand extracting the `JsonProvider`'s `collect` function and place it inside the `Provider` prototype, so it may be normalized and, thus, may be used by other providers to return a normalized result. I agree with that. However, I don't see how these methods add more value to the existing functionality. If an app really requires these methods, then a custom provider may be implemented to provide these values. I'm sorry, but this PR as it stands right now does not convince me.

**Comment by dantman** [comment]
Then could you describe the api for the interface you'd prefer? So I can implement it or propose improvements. Because me implementing abstraction to your library in various ways, each time to be vaguely told it's not the way you'd prefer it to be implemented, is not getting us a solution.

----

JsonProvider's `collect` function is not a simple isolated function that can be pulled out of JsonProvider's implementation into a utility algorithm without some changes to its or Provider's interface.

The `collect` algorithm requires two pieces of information: a list of roles to collect/expand and some macro it can use to map a role to an array of other roles to expand. JsonProvider's implementation handles the second by hardcoding a closure reference to JsonProvider's `_rules` and the data structure it uses.

Provider does not have the concept of a `_rules` object or mapping inheritance. And `_rules` doesn't work for some types of providers. So to move `collect` up to provider, the concept of inheritance mapping needs to come with it in some form.

----

I implemented `getRoles`+`getInheritedRoles` as part of Provider's interface because I expect the JsonProvider-like pattern – of providers that understand user->roles mapping and role->inheritance mapping, but don't care about the recursive structure rbac wants – will be pretty common; and it made sense to make that interface clean and concise for providers, instead of having half the custom provider implementations all start with the boilerplate `getRoles(user) { return this.collect(...` referring to a mystery function. Likewise the interface for providers that worked with a roles tree is just as concise, they just define a `getRoleHierarchy` and ignore `getRoles`/`getInheritedRoles`.

----

Btw, since you consider providers that fetch permissions role info from a database valid, I can think of a situation where inheritance mapping being async would be valid: A provider that gets roles out of a `Role { name:string, inherits:array<string>, permissions:array<string>, attributes:array<string> }` database table.

**Comment by dantman** [comment]
Here's option C,

This one abstracts collect into a utility function separate from provider which accepts a roles array and a function to map role -> inherited roles and returns the role tree.

This keeps the provider interface the same, abstracts away collection for other providers, and provider doesn't need to know about inheritance or rules.

However because JsonProvider's inheritance mapping implementation is part of `getRoles` I'm back to square one since I can't override the user->roles mapping without reimplementing the inheritance mapping function that references JsonProvider's private _rules.

**Comment by yanickrochon** [comment]
I am sorry if I wasn't clear, either in the code or in my comments. And, first, I want to thank you for your interest and contribution. My intention is not to dismiss your efforts. I'll try to make things clearer.

1. The `Provider` interface is intended to provide for the RBAC-A system, and does not serve more purpose, basically. And the RBAC-A implementation only needs 3 things; a **hierarchy of roles** for a given user, and a series of **permissions** and **attributes** for a given role(s). There is no need for other methods as these are the only information required to validating a user; it is the `Provider` implementation's responsibility to provide these values.

2. Adding more methods would only require more function calls and slow the process of validating user rights. Perhaps `getPermissions(role)` and `getAttributes(role)` could be refactored to accept a list of roles and obtain the list of permissions(1) and attributes(2) altogether, this would require much refactoring, but would reduce significantly the number of calls and speed up validation, while not adding more burden on `Provider` implementations (i.e. it would not change the responsibilities of the `Provider`). But this was not brought up in the conversation so far, and focus was more on making the `Provider` more fine grained, which I disagree for the mentioned reasons.

3. This module has a very low dependency footprint, and I intend to keep it that way. The two actual dependencies are in fact not needed, and could very well be removed. The initial intend was to provide custom errors and asynchronous events, but it turns out that either are completely unnecessary for the current implementation. In your last proposal, you make use of `yield` (thus add `co` as a dependency) which breaks the stack trace on error. I have used `co` for the past two years, and I started to replace it whenever I can for the past 6 months now. For the upcoming `async`/`await` feature, using promises is the way to go; the RBAC-A system does not need to be verbose, it needs to be efficient. As for Babel, I agree with many third party module and middleware maintainers, that there is really no need to transpile if the code is future-compliant. Babel only adds too much overhead for not much benefits (i.e. I not yet have seen any benefit of using Babel on third party modules).

Like I said, my goal is not to discourage you or put your efforts down. This module is still young, but yet has a low traffic, meaning that people already use it in their projects. I just don't want it to become heavy, bloated and heterogeneous. I am willing and open to discuss about implementations, even accept changes, as long as these changes are grounded and answer real application issues. Adding a feature to an already functioning implementation, or changing an entire API, on the basis of "it might be useful" is not something that should be accepted lightly.

**Comment by corysimmons** [comment]
https://github.com/yanickrochon/rbac-a/pull/2#issuecomment-221400513

I'd like to see ES2015 syntax as well. If you're worried about performance, a lot of that stuff is natively implemented in Node, but as @dantman mentioned, they can transpile to `function`s as well.

Readability is pretty important, especially for developers interested in contributing to the project.

Also, at a glance, it signifies that the project is designed for use in modern applications. That is, my faith in how well a project is being maintained is greatly diminished when I see ES5 syntax. I'm aware there are a ton of projects still on ES5, and I understand you valuing performance over readability, but just anecdotally, I'm always way more interested in contributing to a project if it's written in ES6.

I'm not sure how applicable it is, but if this ends up getting bundled, users can benefit from Webpack 2's (and Rollup, etc.) [tree-shaking](https://webpack.js.org/guides/tree-shaking/).

>Adding a feature to an already functioning implementation, or changing an entire API, on the basis of "it might be useful" is not something that should be accepted lightly.

I agree with preferring `async`/`await` over `co`. But semver negates your point about adding features or breaking the API doesn't it? API should be discussed (and you guys were doing that), but people shouldn't be afraid to add helpful features that make interacting with the lib easier. Just my 2 cents.

**Sidenote:** Kinda sad that you guys couldn't figure this out. A lot of conversation and work here, but no merge.

**Comment by yanickrochon** [comment]
After much time away from this project, it was about time to revisit! I have completed a 1.0.0, which does not add much to the existing code base, but I will be releasing a 2.0.0 that will be compatible only to Node v12 and up. The 1.0.0 release will be for legacy usage (I did not want to break too much things).

I am closing this as it is both conflicting and also use the [co](https://github.com/tj/co) module which is out of scope for this project, and outdated for all intents and purposes.

See #9 for updates.

**Pull request closed without merging**
